services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: job-portal-postgres-prod
    env_file:
      - ./backend/.env.production
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-jobportal}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - job-portal-network-prod
    restart: unless-stopped

  # Database Migration Service
  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-portal-db-init-prod
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env.production
    environment:
      - UV_CACHE_DIR=/tmp/.uv-cache
    networks:
      - job-portal-network-prod
    command: sh -c "uv run alembic upgrade head"
    restart: no

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-portal-backend-prod
    depends_on:
      postgres:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
    env_file:
      - ./backend/.env.production
    ports:
      - "5000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - job-portal-network-prod
    restart: always

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: job-portal-frontend-prod
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:5173"
    networks:
      - job-portal-network-prod
    restart: always

  # S3-Compatible Object Storage (MinIO)
  minio:
    image: minio/minio:latest
    container_name: job-portal-minio-prod
    env_file:
      - ./.env.minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-krishom}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-ValidPass#3679}
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    volumes:
      - minio_data_prod:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - job-portal-network-prod
    restart: unless-stopped

  # MinIO setup service (creates buckets)
  minio-setup:
    image: minio/mc
    container_name: job-portal-minio-setup-prod
    env_file:
      - ./.env.minio
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - job-portal-network-prod
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-krishom}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-ValidPass#3679}
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; /usr/bin/mc mb --ignore-existing myminio/job-portal-resumes; /usr/bin/mc policy set download myminio/job-portal-resumes; exit 0;"

volumes:
  postgres_data_prod:
    driver: local
  minio_data_prod:
    driver: local

networks:
  job-portal-network-prod:
    driver: bridge
