# Development overrides for Docker Compose
# Use with: docker compose -f compose.yml -f compose.dev.yml up

services:
  backend:
    environment:
      - DEBUG=true
      - PYTHON_ENV=development
      - FASTAPI_RELOAD=true
    volumes:
      - ./backend:/app/backend
      - /app/backend/__pycache__
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  frontend-dev:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
