"""Initial migration

Revision ID: 18988acdd0f6
Revises:
Create Date: 2026-01-21 17:16:34.435659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, DateTime, Boolean, Integer, ForeignKey, Enum


# revision identifiers, used by Alembic.
revision: str = "18988acdd0f6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", Integer(), nullable=False),
        sa.Column("username", String(), nullable=False),
        sa.Column("email", String(), nullable=False),
        sa.Column("hashed_password", String(), nullable=False),
        sa.Column(
            "role", Enum("JOBSEEKER", "EMPLOYER", name="userrole"), nullable=False
        ),
        sa.Column("is_active", Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "job",
        sa.Column("id", Integer(), nullable=False),
        sa.Column("title", String(), nullable=False),
        sa.Column("description", String(), nullable=False),
        sa.Column("location", String(), nullable=False),
        sa.Column("category", String(), nullable=False),
        sa.Column("company", String(), nullable=False),
        sa.Column("employer_id", Integer(), nullable=False),
        sa.Column("created_at", String(), nullable=False),
        sa.Column("updated_at", String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", Integer(), nullable=False),
        sa.Column("job_id", Integer(), nullable=False),
        sa.Column("user_id", Integer(), nullable=False),
        sa.Column("resume_path", String(length=255), nullable=False),
        sa.Column("cover_letter", String(), nullable=True),
        sa.Column("status", String(), nullable=False),
        sa.Column("created_at", DateTime(), nullable=False),
        sa.Column("updated_at", DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_job_id"), "applications", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_job_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_table("job")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
